spring:
  application:
    name: hrms-backend
  profiles:
    active: dev

  jpa:
    defer-datasource-initialization: true

  sql:
    init:
      mode: never

#  sql:
#    init:
#      mode: always

app:
  jwt:
    secret: ${JWT_SECRET:change_me_at_least_256_bits_random_string_for_hmac_sha256}
#    access-token-expiration: 1800000    # 30 minutes
    access-token-expiration: 30000    # 30 seconds
    refresh-token-expiration: 604800000 # 7 days
  encryption:
    key: ${ENCRYPTION_KEY:default-key}
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:4200}

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
